const std = @import("std");

pub const Token = struct {
    tag: Tag,
    start: u32,
    end: u32,

    pub const Tag = enum {
        // Special
        invalid,
        eof,
        statement_end,

        // Literals
        ident,
        integer,
        float,
        string,
        byte_string,
        char,

        // Keywords
        keyword_pub,
        keyword_export,
        keyword_inline,
        keyword_noinline,
        keyword_extern,
        keyword_const,
        keyword_var,
        keyword_threadlocal,
        keyword_fn,
        keyword_comptime,
        keyword_try,
        keyword_anytype,
        keyword_test,
        keyword_if,
        keyword_else,
        keyword_while,
        keyword_for,
        keyword_in,
        keyword_match,
        keyword_return,
        keyword_break,
        keyword_continue,
        keyword_defer,
        keyword_errdefer,
        keyword_unsafe,
        keyword_volatile,
        keyword_align,
        keyword_struct,
        keyword_enum,
        keyword_union,
        keyword_error,
        keyword_packed,
        keyword_nonexhaustive,
        keyword_true,
        keyword_false,
        keyword_null,
        keyword_undefined,
        keyword_type,

        // Punctuation
        comma,
        colon,
        l_paren,
        r_paren,
        l_brace,
        r_brace,
        l_bracket,
        r_bracket,
        dot,
        dot_dot,
        dot_asterisk,
        dot_question,
        arrow,
        at,
        bang,
        question,

        // Arithmetic
        plus,
        minus,
        asterisk,
        slash,
        percent,
        plus_percent,
        minus_percent,
        asterisk_percent,
        plus_pipe,
        minus_pipe,
        asterisk_pipe,

        // Bitwise
        ampersand,
        pipe,
        caret,
        tilde,

        // Comparison
        equal_equal,
        bang_equal,
        angle_bracket_left,
        angle_bracket_left_equal,
        angle_bracket_right,
        angle_bracket_right_equal,

        // Logical
        ampersand_ampersand,
        pipe_pipe,

        // Shifts
        shl,
        shr,
        shl_percent,
        shr_percent,
        shl_pipe,
        shl_percent_pipe,

        // Shift-Combine (Prefix)
        ampersand_shl,
        pipe_shl,
        caret_shl,
        ampersand_shr,
        pipe_shr,
        caret_shr,
        plus_shl,
        minus_shl,
        asterisk_shl,
        plus_percent_shl,
        minus_percent_shl,
        asterisk_percent_shl,
        plus_pipe_shl,
        minus_pipe_shl,
        asterisk_pipe_shl,
        plus_shr,
        minus_shr,
        asterisk_shr,
        plus_percent_shr,
        minus_percent_shr,
        asterisk_percent_shr,
        plus_pipe_shr,
        minus_pipe_shr,
        asterisk_pipe_shr,

        // Shift-Combine (Suffix)
        shl_ampersand,
        shl_caret,
        shr_ampersand,
        shr_pipe,
        shr_caret,

        // Assignments
        equal,
        plus_equal,
        minus_equal,
        asterisk_equal,
        slash_equal,
        percent_equal,
        plus_percent_equal,
        minus_percent_equal,
        asterisk_percent_equal,
        plus_pipe_equal,
        minus_pipe_equal,
        asterisk_pipe_equal,
        ampersand_equal,
        pipe_equal,
        caret_equal,
        shl_equal,
        shr_equal,
        shl_percent_equal,
        shr_percent_equal,
        shl_pipe_equal,
        shl_percent_pipe_equal,

        // Shift-Combine Assignments
        ampersand_shl_equal,
        pipe_shl_equal,
        caret_shl_equal,
        ampersand_shr_equal,
        pipe_shr_equal,
        caret_shr_equal,
        shl_ampersand_equal,
        shl_caret_equal,
        shr_ampersand_equal,
        shr_pipe_equal,
        shr_caret_equal,
        plus_shl_equal,
        minus_shl_equal,
        asterisk_shl_equal,
        plus_percent_shl_equal,
        minus_percent_shl_equal,
        asterisk_percent_shl_equal,
        plus_pipe_shl_equal,
        minus_pipe_shl_equal,
        asterisk_pipe_shl_equal,
        plus_shr_equal,
        minus_shr_equal,
        asterisk_shr_equal,
        plus_percent_shr_equal,
        minus_percent_shr_equal,
        asterisk_percent_shr_equal,
        plus_pipe_shr_equal,
        minus_pipe_shr_equal,
        asterisk_pipe_shr_equal,

        pub fn getKeyword(bytes: []const u8) ?Tag {
            const Map = std.StaticStringMap(Tag).initComptime(.{
                .{ "pub", .keyword_pub },
                .{ "export", .keyword_export },
                .{ "inline", .keyword_inline },
                .{ "noinline", .keyword_noinline },
                .{ "extern", .keyword_extern },
                .{ "const", .keyword_const },
                .{ "var", .keyword_var },
                .{ "threadlocal", .keyword_threadlocal },
                .{ "fn", .keyword_fn },
                .{ "comptime", .keyword_comptime },
                .{ "try", .keyword_try },
                .{ "anytype", .keyword_anytype },
                .{ "test", .keyword_test },
                .{ "if", .keyword_if },
                .{ "else", .keyword_else },
                .{ "while", .keyword_while },
                .{ "for", .keyword_for },
                .{ "in", .keyword_in },
                .{ "match", .keyword_match },
                .{ "return", .keyword_return },
                .{ "break", .keyword_break },
                .{ "continue", .keyword_continue },
                .{ "defer", .keyword_defer },
                .{ "errdefer", .keyword_errdefer },
                .{ "unsafe", .keyword_unsafe },
                .{ "volatile", .keyword_volatile },
                .{ "align", .keyword_align },
                .{ "struct", .keyword_struct },
                .{ "enum", .keyword_enum },
                .{ "union", .keyword_union },
                .{ "error", .keyword_error },
                .{ "packed", .keyword_packed },
                .{ "nonexhaustive", .keyword_nonexhaustive },
                .{ "true", .keyword_true },
                .{ "false", .keyword_false },
                .{ "null", .keyword_null },
                .{ "undefined", .keyword_undefined },
                .{ "type", .keyword_type },
            });
            return Map.get(bytes);
        }
    };
};
