#!/usr/bin/env python3
"""Writes std/src/xkb/keysyms.mlx from the X11 keysym headers in
std/registry/xkb/ (keysymdef.h and the vendor headers).

    tools/materialize_xkb_keysyms.py          writes the file
    tools/materialize_xkb_keysyms.py --check  exits 1 when it is not current

Every keysym name becomes one line of a text table in the generated module:
"NAME VALUE [CODEPOINT]" (hexadecimal), names in the order the headers give
them, so the first name of a value is its canonical one. The code point is
the Unicode character the keysym types, from the headers' "U+xxxx"
comments; it is left out where std.xkb computes it (Latin-1, the 0x01000000
Unicode range) and for keysyms that type nothing.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY = os.path.join(ROOT, 'std', 'registry', 'xkb')
OUTPUT = os.path.join(ROOT, 'std', 'src', 'xkb', 'keysyms.mlx')
HEADERS = ['keysymdef.h', 'XF86keysym.h', 'Sunkeysym.h', 'DECkeysym.h', 'HPkeysym.h']
PREFIXES = [('XF86XK_', 'XF86'), ('SunXK_', 'Sun'), ('DXK_', 'D'), ('hpXK_', 'hp'), ('osfXK_', 'osf'), ('XK_', '')]
# Where libxkbcommon's character table differs from the headers' comments.
CODE_OVERRIDES = {0xabc: 0x27e8, 0xabe: 0x27e9, 0xdde: 0xe3e}
DEFINE = re.compile(r'^#define\s+(\w+)\s+(0x[0-9a-fA-F]+)\s*(?:/\*(.*?)\*/)?')
CODEPOINT = re.compile(r'U\+([0-9A-Fa-f]{4,6})')


def computed(value):
    """Whether std.xkb computes the code point itself (Latin-1, Unicode keysyms)."""
    return 0x20 <= value <= 0x7e or 0xa0 <= value <= 0xff or 0x01000100 <= value <= 0x0110ffff


def entries():
    seen = set()
    result = []
    for header in HEADERS:
        for line in open(os.path.join(REGISTRY, header), encoding='latin-1'):
            m = DEFINE.match(line)
            if not m:
                continue
            macro, value, comment = m.group(1), int(m.group(2), 16), m.group(3) or ''
            name = None
            for prefix, replacement in PREFIXES:
                if macro.startswith(prefix):
                    name = replacement + macro[len(prefix):]
                    break
            if name is None or name in seen:
                continue
            seen.add(name)
            code = None
            c = CODEPOINT.search(comment)
            if c and not computed(value):
                code = int(c.group(1), 16)
            if value in CODE_OVERRIDES:
                code = CODE_OVERRIDES[value]
            result.append((name, value, code))
    # The names libxkbcommon knows beyond these headers.
    for line in open(os.path.join(REGISTRY, 'xkbcommon-extra.txt')):
        if line.startswith('#') or not line.strip():
            continue
        name, value = line.split()
        if name not in seen:
            seen.add(name)
            result.append((name, int(value, 16), None))
    return result


def render():
    lines = []
    for name, value, code in entries():
        lines.append(name + ' ' + format(value, 'x') + ('' if code is None else ' ' + format(code, 'x')))
    table = '\n'.join(lines) + '\n'
    out = []
    out.append('// Generated by tools/materialize_xkb_keysyms.py from the X11 keysym')
    out.append('// headers in std/registry/xkb/ (keysymdef.h, XF86keysym.h, Sunkeysym.h,')
    out.append('// DECkeysym.h, HPkeysym.h); do not edit it by hand.')
    out.append('//')
    out.append('// One keysym a line: "NAME VALUE [CODEPOINT]", hexadecimal. The first name')
    out.append('// of a value is its canonical one. The code point is the character the')
    out.append('// keysym types where std.xkb does not compute it (Latin-1 and the')
    out.append('// 0x01000000 Unicode range are computed).')
    out.append('')
    out.append('pub const COUNT: usize = ' + str(len(lines)))
    out.append('')
    out.append('pub fn table() -> []const u8 {')
    out.append('    return ' + '"' + table.replace('\n', '\\n') + '"')
    out.append('}')
    return '\n'.join(out) + '\n'


def main():
    text = render()
    if '--check' in sys.argv:
        current = open(OUTPUT).read() if os.path.exists(OUTPUT) else ''
        if current != text:
            print('std/src/xkb/keysyms.mlx is not current: run tools/materialize_xkb_keysyms.py')
            return 1
        print('ok   std/src/xkb/keysyms.mlx is current')
        return 0
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    open(OUTPUT, 'w').write(text)
    print('wrote', os.path.relpath(OUTPUT, ROOT), '(' + str(text.count('\n')) + ' lines)')
    return 0


sys.exit(main())
